name: Playwright Smoke Tests

on:
  workflow_dispatch:

jobs:
  run-smoke-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install --with-deps

      - name: Run Smoke Tests
        run:  | 
          npx playwright test --config=tests/nlx --project=smoke
        env:
          SKUID_HOST: ${{ secrets.SKUID_HOST }}
          SKUID_UN: ${{ secrets.SKUID_UN }}
          SKUID_PW: ${{ secrets.SKUID_PW }}
          
      - name: Store Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30