name: Admin Console Tests

on:
  workflow_dispatch:

jobs:
  run-smoke-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install --with-deps

      - name: Run Smoke Tests
        run:  | 
          npx playwright test --config=tests/tacos --project=admin
        env:
          SKUID_HOST: ${{ secrets.SKUID_HOST }}
          
      - name: Store Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: .
          retention-days: 30